### ISSUE TITLE
Testimony section kegedean

### ISSUE THREAD

**Issue by jasonnchann24** [jasonnchann24/bloomwood-project#31]
![image](https://user-images.githubusercontent.com/46631787/134107549-a9ddbd0a-04aa-426d-9f5a-09d9112d6b2e.png)

![image](https://user-images.githubusercontent.com/46631787/134107577-518bcaa7-e4a9-4c53-aab0-279ecdc5538e.png)

di figma testimony cardnya lebih pendek 2 foto dari diatasnya

**Comment by jrchan30** [comment]
iya ini kan waktu itu yg dibahas max char testi.. dikurangin y artinya max charny
