### ISSUE TITLE
Testimony Bg

### ISSUE THREAD

**Issue by michellamonicaa** [jasonnchann24/bloomwood-project#42]
arrow kanan nya bg black 
<img width="281" alt="Screen Shot 2021-09-25 at 16 21 54" src="https://user-images.githubusercontent.com/59686270/134766559-8df61b92-7fbb-4906-badc-824387752ec2.png">

**Comment by jasonnchann24** [comment]
@michellamonicaa itu gak kalau lagi di click?

**Comment by michellamonicaa** [comment]
> @michellamonicaa itu gak kalau lagi di click?

dii klik masi tetep putih ini (?)
