### ISSUE TITLE
Menu Navbar

### ISSUE THREAD

**Issue by michellamonicaa** [jasonnchann24/bloomwood-project#44]
Jadinya di hilangkann
<img width="665" alt="Screen Shot 2021-09-25 at 16 25 12" src="https://user-images.githubusercontent.com/59686270/134766706-0b4aa18f-97b1-4e3f-8ef6-126fbd3b5328.png">
ya

**Comment by jasonnchann24** [comment]
@michellamonicaa udah di apuzh 🚀
